version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ec2-user/backend

hooks:
  AfterInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: backend/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
